### ISSUE TITLE
Problem? 

### ISSUE THREAD

**Issue by anggaxd** [anggaxd/cfbid#1]
If There Are Problems Please Comment Below

**Comment by anggaxd** [comment]
Nice

**Comment by Lord-KAZUMA-hub** [comment]
~ $ cd cfbid
~/cfbid $ python2 crack.py
Traceback (most recent call last):
  File "avs.py", line 62437, in <module>
  File "anggaxd", line 3, in <module>
ImportError: No module named requests

Problem

**Comment by Condet244** [comment]
Tidak bisa buat username
